-- Additional Sample Alumni Data
INSERT INTO alumni (
  name,
  linkedin_url,
  picture_url,
  bio,
  role,
  companies,
  industry,
  big_brother,
  little_brothers,
  family_branch,
  graduation_year,
  location,
  has_linkedin,
  scraped,
  manually_verified,
  source_sheet
) VALUES
  (
    'Alex Kim',
    'https://linkedin.com/in/alexkim',
    NULL,
    'Loves building products that scale.',
    'Product Manager',
    ARRAY['Google', 'Meta'],
    'Technology',
    'Emily Chen',
    ARRAY['Priya Patel'],
    'Lambda',
    2017,
    'San Francisco, CA',
    true,
    true,
    false,
    'Generated'
  ),
  (
    'Priya Patel',
    'https://linkedin.com/in/priyapatel',
    NULL,
    'Turning data into actionable insights.',
    'Data Scientist',
    ARRAY['Amazon'],
    'Technology',
    'Alex Kim',
    ARRAY['David Nguyen'],
    'Omega',
    2019,
    'Seattle, WA',
    true,
    true,
    false,
    'Generated'
  ),
  (
    'Michael Chen',
    'https://linkedin.com/in/michaelchen',
    NULL,
    'Strategy and operations expert.',
    'Consultant',
    ARRAY['McKinsey', 'Deloitte'],
    'Consulting',
    'Sarah Williams',
    ARRAY['Jessica Lee'],
    'Gamma',
    2015,
    'New York, NY',
    true,
    true,
    false,
    'Generated'
  ),
  (
    'Jessica Lee',
    'https://linkedin.com/in/jessicalee',
    NULL,
    'Creative marketing for global brands.',
    'Marketing Manager',
    ARRAY['Apple'],
    'Marketing',
    'Michael Chen',
    ARRAY['David Nguyen'],
    'Lambda',
    2018,
    'Los Angeles, CA',
    true,
    true,
    false,
    'Generated'
  ),
  (
    'David Nguyen',
    'https://linkedin.com/in/davidnguyen',
    NULL,
    'Full-stack developer and open source enthusiast.',
    'Software Engineer',
    ARRAY['Microsoft'],
    'Technology',
    'Jessica Lee',
    ARRAY['Sara Johnson'],
    'Omega',
    2020,
    'Austin, TX',
    true,
    true,
    false,
    'Generated'
  ),
  (
    'Sara Johnson',
    'https://linkedin.com/in/sarajohnson',
    NULL,
    'Finance and analytics specialist.',
    'Business Analyst',
    ARRAY['Goldman Sachs'],
    'Finance',
    'David Nguyen',
    ARRAY['Carlos Martinez'],
    'Gamma',
    2016,
    'Chicago, IL',
    true,
    true,
    false,
    'Generated'
  ),
  (
    'Carlos Martinez',
    'https://linkedin.com/in/carlosmartinez',
    NULL,
    'Managing teams and delivering results.',
    'Project Manager',
    ARRAY['JPMorgan'],
    'Finance',
    'Sara Johnson',
    ARRAY['Emily Davis'],
    'Lambda',
    2014,
    'Boston, MA',
    true,
    true,
    false,
    'Generated'
  ),
  (
    'Emily Davis',
    'https://linkedin.com/in/emilydavis',
    NULL,
    'Connecting customers with solutions.',
    'Sales Representative',
    ARRAY['Amazon', 'Apple'],
    'Technology',
    'Carlos Martinez',
    ARRAY['Brian O''Connor'],
    'Omega',
    2021,
    'New York, NY',
    true,
    true,
    false,
    'Generated'
  ),
  (
    'Brian O''Connor',
    'https://linkedin.com/in/brianoconnor',
    NULL,
    'Improving healthcare systems.',
    'Healthcare Consultant',
    ARRAY['Deloitte'],
    'Healthcare',
    'Emily Davis',
    ARRAY['Aisha Hassan'],
    'Gamma',
    2013,
    'San Francisco, CA',
    true,
    true,
    false,
    'Generated'
  ),
  (
    'Aisha Hassan',
    'https://linkedin.com/in/aishahassan',
    NULL,
    'Passionate about education reform.',
    'Education Specialist',
    ARRAY['Non-Profit Org'],
    'Education',
    'Brian O''Connor',
    ARRAY['John Smith'],
    'Lambda',
    2012,
    'Washington DC',
    true,
    true,
    false,
    'Generated'
  ); 