-- Sample Alumni Data
INSERT INTO alumni (
  name,
  linkedin_url,
  picture_url,
  bio,
  role,
  companies,
  industry,
  big_brother,
  little_brothers,
  family_branch,
  graduation_year,
  location,
  has_linkedin,
  scraped,
  manually_verified,
  source_sheet
) VALUES
  (
    'John Smith',
    'https://linkedin.com/in/johnsmith',
    'https://i.pravatar.cc/300?img=1',
    'Finance professional with 5 years of experience in investment banking. Passionate about mentoring younger brothers.',
    'Senior Investment Banker',
    ARRAY['Goldman Sachs', 'JP Morgan'],
    'Finance',
    'Michael Johnson',
    ARRAY['David Lee', 'Sarah Chen'],
    'Lambda',
    2018,
    'New York, NY',
    true,
    true,
    true,
    'Initial Import'
  ),
  (
    'Emily Chen',
    'https://linkedin.com/in/emilychen',
    'https://i.pravatar.cc/300?img=2',
    'Tech entrepreneur and former Google engineer. Founded two successful startups.',
    'CEO & Founder',
    ARRAY['TechStart', 'Google'],
    'Technology',
    'Robert Wilson',
    ARRAY['Alex Kim'],
    'Omega',
    2019,
    'San Francisco, CA',
    true,
    true,
    true,
    'Initial Import'
  ),
  (
    'Michael Johnson',
    'https://linkedin.com/in/michaeljohnson',
    'https://i.pravatar.cc/300?img=3',
    'Consulting professional with expertise in healthcare strategy.',
    'Senior Consultant',
    ARRAY['McKinsey', 'Deloitte'],
    'Healthcare',
    'James Brown',
    ARRAY['John Smith'],
    'Lambda',
    2016,
    'Chicago, IL',
    true,
    true,
    true,
    'Initial Import'
  ),
  (
    'Sarah Williams',
    'https://linkedin.com/in/sarahwilliams',
    'https://i.pravatar.cc/300?img=4',
    'Marketing executive with experience in consumer goods and digital marketing.',
    'Marketing Director',
    ARRAY['Procter & Gamble', 'Nike'],
    'Marketing',
    'Lisa Anderson',
    ARRAY['Emma Davis'],
    'Gamma',
    2020,
    'Los Angeles, CA',
    true,
    true,
    true,
    'Initial Import'
  ),
  (
    'David Lee',
    'https://linkedin.com/in/davidlee',
    'https://i.pravatar.cc/300?img=5',
    'Software engineer specializing in machine learning and AI.',
    'Senior Software Engineer',
    ARRAY['Microsoft', 'Amazon'],
    'Technology',
    'John Smith',
    ARRAY['Kevin Park'],
    'Lambda',
    2021,
    'Seattle, WA',
    true,
    true,
    true,
    'Initial Import'
  ); 